In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
## Sentences

sent = [
    'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
]

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
## Defining the vocabulary size

voc_size = 10000

In [37]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [38]:
## One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9274, 1301, 6683, 5322],
 [9274, 1301, 6683, 3665],
 [9274, 3422, 6683, 572],
 [5457, 6540, 2358, 753, 1838],
 [5457, 6540, 2358, 753, 6969],
 [8369, 9274, 8799, 6683, 7373],
 [2081, 2636, 977, 753]]

In [39]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [40]:
sent_length = 8
embedded_docs = pad_sequences(
    one_hot_repr,
    padding='pre', #zeros in the starting
    maxlen=sent_length
    )
print(embedded_docs)

[[   0    0    0    0 9274 1301 6683 5322]
 [   0    0    0    0 9274 1301 6683 3665]
 [   0    0    0    0 9274 3422 6683  572]
 [   0    0    0 5457 6540 2358  753 1838]
 [   0    0    0 5457 6540 2358  753 6969]
 [   0    0    0 8369 9274 8799 6683 7373]
 [   0    0    0    0 2081 2636  977  753]]


In [41]:
## feature representation
dim = 10

In [42]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [43]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([[[-4.40680645e-02, -3.28970440e-02,  2.99364664e-02,
         -3.88456509e-03, -1.65728815e-02, -1.80906542e-02,
         -4.78493832e-02,  3.32427137e-02,  2.44504549e-02,
         -4.40465808e-02],
        [-4.40680645e-02, -3.28970440e-02,  2.99364664e-02,
         -3.88456509e-03, -1.65728815e-02, -1.80906542e-02,
         -4.78493832e-02,  3.32427137e-02,  2.44504549e-02,
         -4.40465808e-02],
        [-4.40680645e-02, -3.28970440e-02,  2.99364664e-02,
         -3.88456509e-03, -1.65728815e-02, -1.80906542e-02,
         -4.78493832e-02,  3.32427137e-02,  2.44504549e-02,
         -4.40465808e-02],
        [-4.40680645e-02, -3.28970440e-02,  2.99364664e-02,
         -3.88456509e-03, -1.65728815e-02, -1.80906542e-02,
         -4.78493832e-02,  3.32427137e-02,  2.44504549e-02,
         -4.40465808e-02],
        [-1.06653944e-02, -3.66449580e-02,  4.41502668e-02,
          2.68928893e-02,  1.65117271e-02,  1.03571899e-02,
         -4.48679924e-02, -4.10822257e-02,  3.092763

In [45]:
embedded_docs[0]

array([   0,    0,    0,    0, 9274, 1301, 6683, 5322], dtype=int32)